export default {
  setup: {},
  data: [
    { name: "Action", value: 0 },
    { name: "Adventure", value: 0 },
    { name: "Demons", value: 0 },
    { name: "Drama", value: 0 },
    { name: "Fantasy", value: 0 },
    { name: "Horror", value: 0 },
    { name: "Military", value: 0 },
    { name: "Romance", value: 0 },
    { name: "Seinen", value: 0 },
    { name: "Supernatural", value: 0 },
    { name: "Ecchi", value: 0 },
    { name: "Sci-Fi", value: 0 },
    { name: "Comedy", value: 0 },
    { name: "Mecha", value: 0 },
    { name: "Space", value: 0 },
    { name: "Music", value: 0 },
    { name: "Shounen", value: 0 },
    { name: "Slice of Life", value: 0 },
    { name: "Psychological", value: 0 },
    { name: "Sports", value: 0 },
    { name: "Shoujo", value: 0 },
    { name: "Police", value: 0 },
    { name: "Magic", value: 0 },
    { name: "Mystery", value: 0 },
    { name: "Game", value: 0 },
    { name: "Historical", value: 0 },
    { name: "Samurai", value: 0 },
    { name: "Martial Arts", value: 0 },
    { name: "Demons", value: 0 },
    { name: "Vampire", value: 0 },
    { name: "School", value: 0 },
    { name: "Super Power", value: 0 },
    { name: "Thriller", value: 0 },
    { name: "Cars", value: 0 },
    { name: "Josei", value: 0 },
    { name: "Harem", value: 0 }
  ]
}